// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using datapleasework.Data;

namespace datapleasework.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20190625092242_1234567")]
    partial class _1234567
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099");

            modelBuilder.Entity("datapleasework.Models.Assignee", b =>
                {
                    b.Property<long>("AssId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssigneeName");

                    b.HasKey("AssId");

                    b.ToTable("Assignees");
                });

            modelBuilder.Entity("datapleasework.Models.Todo", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("AssigneeAssId");

                    b.Property<short>("IsDone");

                    b.Property<short>("IsUrgent");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.HasIndex("AssigneeAssId");

                    b.ToTable("Todos");
                });

            modelBuilder.Entity("datapleasework.Models.Todo", b =>
                {
                    b.HasOne("datapleasework.Models.Assignee", "Assignee")
                        .WithMany("TodoList")
                        .HasForeignKey("AssigneeAssId");
                });
#pragma warning restore 612, 618
        }
    }
}
